[application]

[bundle]
identifier = "com.snikhil-vaddhi.space-invaders"
name = "Space Invaders"
version = "0.1.0"
publisher = "SNikhil-Vaddhi"

[web.app]
# HTML title tag content
title = "space_invaders"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
